### ISSUE TITLE
Peer review Repository

### ISSUE THREAD

**Issue by HappyPantss** [veerleprins/frontend-data#1]
Hey Veerle! 

## Repository
**Checklist voor je repo:**
:heavy_check_mark: Is the repo called exactly 'frontend-data'?
:heavy_check_mark: .gitignore
:heavy_check_mark: Link to live demo on github pages
:heavy_check_mark: Description
**Feedback:** Duidelijke beschrijving van wat de opdracht inhoud!
:heavy_check_mark: Concept
**Feedback:** Geen idee of dit moet, maar je concept staat niet in je README, wel in je wiki!.. Je concept is erg duidelijk, goed dat je bent gaan veranderen na wat feedback! 
:x: image
**Feedback:** Laat doormiddel van een afbeelding zien hoe je visualisatie eruit ziet (als hij volledig klaar is natuurlijk!)
:x: link to example used to build visualization (screenshots)
**Feedback:** Geen idee of het tussen je bronnen staat, maar zet een linkje neer (of een screenshot) van het voorbeeld dat je gebruikt als visualisatie.
:x: Concept described in readme? **(zoals verteld in feedback puntje 'Concept'.. zet niet alles er in, maar een belangrijk stuk)**
:heavy_check_mark: Research question
:heavy_check_mark: Data to be used
:x: Sketch of datavisualization.
:x::heavy_check_mark: Data used described properly? (what's done with invalid and empty values?)
**Feedback:** Je hebt mooi beschreven welke datasets je gebruikt, probeer alleen nog even te vertellen wat je met de data hebt gedaan (wat heb je gedaan met invalid en lege values?)
:heavy_check_mark: plagiarism and acknowledgements
**Feedback:** Je hebt de bronnen mooi in APA style neergezet! Check voor jezelf natuurlijk even of alles klopt

## Wiki
:heavy_check_mark: Can you follow the datacleaning and transforming process?
**Feedback:** Erg duidelijk uitgelegd wat je gebruikt, en wat de functies doen! Misschien kan je nog vertellen waarom alle strings naar integer of floats veranderd moeten worden!
:x: Is there an example of a data object before and after this process?
**Feedback:** Laat oude en nieuwe data zien! Hoe zag de 'vieze' data eruit, en hoe na het schoonmaken? (Screenshot van je console.log bijvoorbeeld)
:question: Is the update pattern (data flow) documented?
Feedback: Ik snap niet zo goed wat er bedoeld word met deze vraag. Maar als ik kijk naar je 'Transforming the Datasets' kan ik zien wat je aan het doen bent wat betreft 'updaten' van de data.
:x::heavy_check_mark: Are there pages documenting what the student learned
**Feedback:** Goed dat je een nieuwe pagina hebt met feedback, hier staan wat dingen in wat je kon veranderen aan je opdracht. Ook heb je een logboek! Alleen mis ik ergens een pagina, of een hoofdstuk met 'wat heb ik nou precies geleerd?'. Kijk waar je dit plaatst.

## Live demo
:heavy_check_mark: Does the visualization makes sense on it's own? (labels, axis, titles)
:x: Does the data shown change through interaction?

## Algemeen
Je wiki, code en demo zien er allemaal erg netjes uit, dit moet wel goed komen! De meeste :x: puntjes zijn kleine dingen die nog even aangepast/ toegevoegd moeten worden. Begrijp je niet waarom ik het goed of 'slecht' vond, bericht mij dan even :). Goed bezig!~

**Comment by veerleprins** [comment]
Thanks for the feedback @HappyPantss ! I have now changed my wiki, readme and code 😄
